application: Choremaster
version: 1
deploy: true
pub: true
dart2js: false 

handlers:
# ************************************** # 
# Handlers for /users resource
# ************************************** # 
- url: ^/users/points/(.*)$ 
  handler: GET:resources/users.dart:Users.getPoints

- url: ^/users/points/(.*)\/(.*)$  
  handler: POST:resources/users.dart:Users.addPoints
  
- url: ^/users/points/(.*)\/(.*)$  
  handler: DELETE:resources/users.dart:Users.removePoints
    
- url:  ^/users/(.*)$
  handler: GET:resources/users.dart:Users.get 

- url: ^/users/(.*)$ 
  handler: POST:resources/users.dart:Users.create  

- url: /users
  handler: GET:resources/users.dart:Users.getAll
  
# ************************************** # 
# Handlers for /tasks resource  
# ************************************** # 
- url: ^/tasks/(.*)$ 
  handler: GET:resources/tasks.dart:Tasks.getState

- url: ^/tasks/(.*)$ 
  handler: POST:resources/tasks.dart:Tasks.setState  
  
- url: /tasks
  handler: GET:resources/tasks.dart:Tasks.getAll

# ************************************** # 
# Handlers for /activities resource
# ************************************** # 
- url:  ^/activities/(.*)$
  handler: GET:resources/activities.dart:Activities.get 

- url: ^/activities/(.*)$ 
  handler: POST:resources/activities.dart:Activities.create  

- url: /activities
  handler: GET:resources/activities.dart:Activities.getAll
  
# ************************************** #   
# Handlers for /logs resource
# ************************************** # 
- url:  ^/logs/(.*)$
  handler: GET:resources/logs.dart:Logs.get 

- url: ^/logs/(.*)$ 
  handler: POST:resources/logs.dart:Logs.create 

- url: /logs
  handler: GET:resources/logs.dart:Logs.getAll
# ************************************** # 

# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web

