application: Vane-Angular-Mongo-Todo
version: 1
deploy: true
pub: true
dart2js: true 

handlers:
- url: /todos 
  handler: GET:todo.dart:Todo.getAll 

- url: /todos 
  handler: POST:todo.dart:Todo.add

- url: /todos 
  handler: PUT:todo.dart:Todo.update

- url: /todos 
  handler: DELETE:todo.dart:Todo.delete 

- url: /users 
  handler: GET:resources/users.dart:Users.getAll 
  
# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web

