application: Choremaster
version: 1
deploy: true
pub: true
dart2js: false 

handlers:
- url: /todos 
  handler: GET:todo.dart:Todo.getAll 

- url: /todos 
  handler: POST:todo.dart:Todo.add

- url: /todos 
  handler: PUT:todo.dart:Todo.update

- url: /todos 
  handler: DELETE:todo.dart:Todo.delete 

# Handlers for /users resource
- url: ^/users/points/(.*)$ 
  handler: GET:resources/users.dart:Users.getPoints

- url: ^/users/points/(.*)$  
  handler: POST:resources/users.dart:Users.addPoints
    
- url:  ^/users/(.*)$
  handler: GET:resources/users.dart:Users.get 

- url: ^/users/(.*)$ 
  handler: POST:resources/users.dart:Users.create  

- url: /users
  handler: GET:resources/users.dart:Users.getAll
    
# Static content, will be served by your app's Nginx instance 
- url: /
  match: postregex
  static_dir: web

